### ISSUE TITLE
Question: how to connect with android device to the server?

### ISSUE THREAD

**Issue by Arsalan0098** [iw4p/OpenConnect-VPN-Server#11]
Hello man, I set the VPN server up and I am able to connect to it with  OpenConnect application. now I was wondering how can I connect to the server with android devices?
Thanks

**Comment by iw4p** [comment]
Hello,
Read the README carefully. I mentioned that you can use AnyConnect client.

**Comment by Arsalan0098** [comment]
Thank you man, I could connect to the server via AnyConnect now but there is no internet connection.

**Comment by iw4p** [comment]
You're welcome.
First of all, make sure you can ping your server through your current internet network (without VPN) and be assured the ocserv configured successfully, and it works fine on at least one device (It can be your laptop or mobile phone).
After that, if you are confident it configured fine, you can understand that the problem is client.
Also, I suggest you to try configuring ocserv via Docker instruction, which is added yesterday.
Then, try other clients and search for OpenVPN clients or ocserv clients like [this](https://ocserv.gitlab.io/www/clients.html).

**Comment by Arsalan0098** [comment]
I did download the application you shared and as soon as i click on connect, application will get closed (without error or anything).
I am using the same net as my pc and i have ping on my mobile device.

**Comment by iw4p** [comment]
May I know how did you configure it? By dockerfile or script?

**Comment by amirtstackoverflow** [comment]
Same problem here! I did install the ocserv by script and, it does connect to vpn by PC BUT it doesn't connect when I try it with Android Devices!!! can you help us we are stuck in a very bad situation

**Comment by iw4p** [comment]
Try OpenConnect on Android. Or share the PC’s VPN if you’re using win 10 or 11, or use Connectify if you’re using windows 8 or older versions.
