### ISSUE TITLE
After a couple of days, traffic is not going through the vpn server

### ISSUE THREAD

**Issue by ber-serker** [iw4p/OpenConnect-VPN-Server#22]
So when I run the script on my server, everything is fine for 2 or 3 days. But after that, my IP address doesn't change when I connect to the server. It seems like the traffic is not going through the VPN server and something is wrong with the routing. I compared the logs from the first and last day. No differences.

**Comment by iw4p** [comment]
Did you restart the ocserv from sysctl (if you are not using docker, if you are using docker just restart your container)? What about uninstalling an installing?

**Comment by ber-serker** [comment]
I restarted the ocserv service but nothing happened. I reinstalled it and it just works for two days and the same problem appeares.

**Comment by iw4p** [comment]
So you installed ocserv via script? Can you try Docker?

**Comment by ber-serker** [comment]
I will keep you posted on the docker method's result. Thanks for the immediate response.

**Comment by iw4p** [comment]
You're welcome!

**Comment by ber-serker** [comment]
I installed the docker. The connection works for two minutes but it gets disconnected. It doesn't last more than two minutes.

**Comment by iw4p** [comment]
Therefore, we can conclude that the important factor is ocserv.conf. Because the Dockerfile uses different ocserv.conf than the script. I suggest you to check [this out](https://ocserv.gitlab.io/www/recipes-ocserv-configuration-basic.html) and change ocserv.conf parameters, and recreate your docker container with new ocserv.conf.

**Comment by ber-serker** [comment]
I changed some options in ocserv.conf. The problem is when I reboot the server, docker is not functioning in the way it was before the reboot. I get this error. 
Error response from daemon: Container d0c9975a3d7edc1c46946b80733c595804cedc21e478bf153aa84ede3151da9e is not running
And vpn is not connecting anymore. 
I tried to start the docker and nothing happened. Actually, I'm not the docker expert but after restarting the server, you need some knowledge about dockers to run that service again.

**Comment by iw4p** [comment]
Yes actually you need to know some of the basic commands of Docker. Git clone the whole project into a directory. Then try to build an image with Dockerfile (search build docker image from dockerfile). 
Then after you make your image from the Dockerfile, you need to make a container from it, so search for create docker container from an image. After that you can create and run it. Each time you modify the ocserv.conf file in the project directory, you need to build the docker file and run it again. 

Don't forget to docker rmi (remove instance). It's important to remove your previous running docker container and then start a new one, because of port conflicts.
