### ISSUE TITLE
how disable GET auth response in browser?

### ISSUE THREAD

**Issue by kvadrakot** [iw4p/OpenConnect-VPN-Server#7]
Hello. I don't know if this is the right place to ask the question.

I am using ocserv 1.1.3 for Rocky linux. And if I follow the authorization link in the browser, I will get the browser's xml response.(GET 200 ok)

```
<config-auth client="vpn" type="auth-request">
<version who="sg">0.1(1)</version>
<auth id="main">
<message>Please enter your username.</message>
<form method="post" action="/auth"> </form>
</auth>
</config-auth> 
```

This is strange, because I do not use a browser for authorization, but use a special client program. How can I disable the display of the authorization message in the browser or replace it with my own custom message? I don’t need other people to know that I had a vpn on port 443, and the message in the browser unmasks this

**Comment by iw4p** [comment]
Hello,
Are you sure you didn't run any other script before or after this script?
Because it seems you used [this script](https://gist.github.com/horsley/e286276f83cae9b60d98) or something similar to this.
Because I don't think the [OpenConnect-VPN script](https://github.com/iw4p/OpenConnect-VPN-Server) does not create such a thing.

**Comment by kvadrakot** [comment]
Hello. I apologize, I created the question in the wrong place. It's really not that script. Thanks!
